/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface IntOverlay {
    'header': string;
    'left': string;
    'modal': boolean;
    'top': string;
  }
}

declare global {


  interface HTMLIntOverlayElement extends Components.IntOverlay, HTMLStencilElement {}
  var HTMLIntOverlayElement: {
    prototype: HTMLIntOverlayElement;
    new (): HTMLIntOverlayElement;
  };
  interface HTMLElementTagNameMap {
    'int-overlay': HTMLIntOverlayElement;
  }
}

declare namespace LocalJSX {
  interface IntOverlay {
    'header'?: string;
    'left'?: string;
    'modal'?: boolean;
    'top'?: string;
  }

  interface IntrinsicElements {
    'int-overlay': IntOverlay;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'int-overlay': LocalJSX.IntOverlay & JSXBase.HTMLAttributes<HTMLIntOverlayElement>;
    }
  }
}


